name: CI
 
on:
  push:
    branches:
      - main
      - develop
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
 
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
 
      - name: Install Dependencies
        run: npm install
 
      - name: Lint with ESLint
        run: npm run lint
 
      - name: Test with Jest
        run: npm test
 
  publish:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
 
    steps:
      - uses: actions/checkout@v2
 
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
          registry-url: https://registry.npmjs.org/
 
      - name: Install Dependencies
        run: npm install
 
      - name: Build
        run: npm run build
 
      - name: Publish to NPM
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
